#伺服器 Port
server.port=8080

#MSSQL Server 連線設定
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ticket_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1111
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#JPA / Hibernate 設定
#update: 啟動時自動根據 Java Entity 建立或更新資料表結構
spring.jpa.hibernate.ddl-auto=update

#顯示執行的 SQL 語法在 Console (方便除錯)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#指定 MS SQL 方言
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect